import Head from 'next/head'

export default function CommonHead() {
  return (
    <Head>
      <title>Unogram</title>
      <meta name="description" content="Generated by create next app" />
      <meta
        name="viewport"
        content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=5.0"
      />
      <meta name="description" content="Unigram app by @ilerofeev" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}
