import Head from 'next/head'
import Header from '../components/Header'
import Sidebar from '../components/sidebar'
import Timeline from '../components/Timeline'
import LoggedInUserContext from '../context/loggedInUser'
import useUser from '../hooks/use-user'
import { User } from 'firebase/auth'
import { useRouter } from 'next/router'
import { useEffect } from 'react'
import * as ROUTES from '../constants/routes'

export default function Dashboard({ user: loggedInuser }: { user: User }) {
  const router = useRouter()
  const { user } = useUser(loggedInuser?.uid)

  useEffect(() => {
    if (!!!loggedInuser) router.push(ROUTES.SIGNIN)

    document.title = 'Unogram'
  }, [router, loggedInuser])

  return (
    user.userId && (
      <>
        <Head>
          <title>Unogram</title>
          <meta name="description" content="Generated by create next app" />
          <meta
            name="viewport"
            content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=5.0"
          />
          <meta name="description" content="Unigram app by @ilerofeev" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          <LoggedInUserContext.Provider value={{ user }}>
            <div className="bg-gray-background">
              <Header />
              <div className="grid grid-cols-3 gap-4 justify-between mx-auto max-w-screen-lg">
                <Timeline />
                <Sidebar />
              </div>
            </div>
          </LoggedInUserContext.Provider>
        </main>
      </>
    )
  )
}
